name: Create release

on:
  push:
    branches:
      - master # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-18.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v1
      - name: "Generate changelog"
        id: generate-changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1
        with:
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"
      - name: "Create GitHub release"
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          draft: true
          prerelease: false